### ISSUE TITLE
"Can't find bundle ..." error during execution

### ISSUE THREAD

**Issue by moderski** [jacekkow/pzsigner-deb#2]
When I try to run the pzsigner application I have got the following error message:
xxxxxxx@xxxxxx:~$ pzsigner 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.pentacomp.signer.Application.initialize(Application.java:65)
	at com.pentacomp.signer.Application.run(Application.java:51)
	at com.pentacomp.signer.Application.main(Application.java:41)
Caused by: java.util.MissingResourceException: Can't find bundle for base name application, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at com.pentacomp.signer.Resources.<clinit>(Resources.java:12)
	... 3 more

**Comment by jacekkow** [comment]
This application only works with system language set to pl.
I have added an override that forces this value in JVM.
DEB is avaliable at: https://github.com/jacekkow/pzsigner-deb/releases/tag/v1.0-4
