### ISSUE TITLE
what is the pkcs11 library that debian loads?

### ISSUE THREAD

**Issue by kalmarek** [jacekkow/pzsigner-deb#3]
Sorry, this is less of an issue and more of a question

https://github.com/jacekkow/pzsigner-deb/blob/20280ea9a50e02b701155805d0f77b9fdd0d33fb/pzsigner#L8

there is a reference to `PKCS11_LIBRARY` env variable. What should I set it to?
is it the systems e.g. `/usr/lib/opensc-pkcs11.so` or the one provided by the authority?

**Comment by kalmarek** [comment]
I've tried setting this to `/opt/proCertumCardManager/cryptoCertum3PKCS-2.0.0.43.r2-MS.so` but `pzsigner` produces (upon "Krok 4"):

```
$ ./pzsigner.sh  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.pentacomp.signer.KeyStoreManager (file:/home/kalmar/pzsigner/x86_64/pz-signer-1.0-SNAPSHOT.jar) to method sun.security.pkcs11.wrapper.PKCS11.getInstance(java.lang.String,java.lang.String,sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS,boolean)
WARNING: Please consider reporting this to the maintainers of com.pentacomp.signer.KeyStoreManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
!!! slot 1
java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
        at java.base/java.lang.Class.getConstructor0(Class.java:3350)
        at java.base/java.lang.Class.getConstructor(Class.java:2152)
        at com.pentacomp.signer.KeyStoreManager.createPkcs11Provider(KeyStoreManager.java:225)
        at com.pentacomp.signer.KeyStoreManager.process(KeyStoreManager.java:93)
        at com.pentacomp.signer.KeyStoreManager.init(KeyStoreManager.java:67)
        at com.pentacomp.signer.KeyStoreManager.initialize(KeyStoreManager.java:50)
        at com.pentacomp.signer.SigningDialog.run(SigningDialog.java:75)
        at com.pentacomp.signer.Application.showSigningDialog(Application.java:136)
        at com.pentacomp.signer.Application.access$400(Application.java:28)
        at com.pentacomp.signer.Application$1.widgetSelected(Application.java:102)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at com.pentacomp.signer.Application.handleEvents(Application.java:183)
        at com.pentacomp.signer.Application.run(Application.java:54)
        at com.pentacomp.signer.Application.main(Application.java:41)
java.security.GeneralSecurityException: Błąd podczas ładowania keystore'a
        at com.pentacomp.signer.KeyStoreManager.init(KeyStoreManager.java:81)
        at com.pentacomp.signer.KeyStoreManager.initialize(KeyStoreManager.java:50)
        at com.pentacomp.signer.SigningDialog.run(SigningDialog.java:75)
        at com.pentacomp.signer.Application.showSigningDialog(Application.java:136)
        at com.pentacomp.signer.Application.access$400(Application.java:28)
        at com.pentacomp.signer.Application$1.widgetSelected(Application.java:102)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at com.pentacomp.signer.Application.handleEvents(Application.java:183)
        at com.pentacomp.signer.Application.run(Application.java:54)
        at com.pentacomp.signer.Application.main(Application.java:41)
Caused by: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
        at java.base/java.lang.Class.getConstructor0(Class.java:3350)
        at java.base/java.lang.Class.getConstructor(Class.java:2152)
        at com.pentacomp.signer.KeyStoreManager.createPkcs11Provider(KeyStoreManager.java:225)
        at com.pentacomp.signer.KeyStoreManager.process(KeyStoreManager.java:93)
        at com.pentacomp.signer.KeyStoreManager.init(KeyStoreManager.java:67)
        ... 14 more
```
even though
```
pkcs11-tool --module /opt/proCertumCardManager/cryptoCertum3PKCS-2.0.0.43.r2-MS.so -O
Using slot 0 with a present token (0x1)
Public Key Object; RSA 2048 bits
  label:      
  ID:         f5488cc54dc2cba8e4d01ef61d39029091801337
  Usage:      encrypt, verify, wrap
  Access:     local
Public Key Object; RSA 2048 bits
  label:      
  ID:         e57c4006a7d8cc7082a231e4a7695bc631bb92c6
  Usage:      encrypt, verify, wrap
  Access:     local
Public Key Object; RSA 2048 bits
  label:      
  ID:         c47d0dca7a82ae635e1d7775e6bdc54f8e0d8d98
  Usage:      encrypt, verify, wrap
  Access:     local
Certificate Object; type = X.509 cert
  label:      
  subject:    [ ... ]
  ID:         [ ... ]
```

**Comment by jacekkow** [comment]
Regarding the first question: the library to load should be provided by your qualified certificate vendor.
For Asseco/Certum: download and install proCertum SmartSign (https://www.certum.pl/pl/wsparcie/cert_oferta_procertum_smart_sign/) and point to `libcryptoCertum3PKCS.so` in the installation directory.
For CenCert: download and install PEM-HEART (https://www.cencert.pl/Oprogramowanie%20PEMHEART/) and point to `libencartp11.so`.
For KIR: download and install .so library (https://www.elektronicznypodpis.pl/informacje/aplikacje/) and point to it (`libccpkip11.so`).
For PWPW (Sigillum) and Eurocert I don't see any apps nor libs for Linux.

I successfully use it with `SS-8.1.21.0-dist/libcryptoCertum3PKCS.so`.

**Comment by jacekkow** [comment]
```
$ ./pzsigner.sh  
```
Where did you get that command from? My package installs "global" `pzsigner` helper, without any extension, `.sh` in particular.
From the stack trace it looks like you are missing the required override for Java 9+ (https://github.com/jacekkow/pzsigner-deb/blob/master/src/com/pentacomp/signer/KeyStoreManager.java), which makes ` com.pentacomp.signer.KeyStoreManager.createPkcs11Provider` call either `createPkcs11ProviderJava8` or `createPkcs11ProviderJava9` depending on version of Java - both of which are absent from provided stack trace.

Are you using the version provided by ePUAP? That won't work. And it is precisely why I have created this repo. Please install this package: https://github.com/jacekkow/pzsigner-deb/releases/download/v1.0-4/pzsigner_1.0-4_amd64.deb and just run `pzsigner`.

**Comment by kalmarek** [comment]
Thanks for the prompt answer and the tip; I can confirm it's running now (on Arch it's enough to unpack `pzsigner_*_amd64.deb/data.tar.xz/opt` into `/opt/`, place `[...]/usr/bin/pzsigner` wherever you need and create `/etc/default/pzsigner` containing `PKCS11_LIBRARY=...`)

Thank you so much for creating this package!
